import { Geist, Geist_Mono, Inter_Tight } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import GetStart from "@/rendering/home/getStart";

const interSans = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: 'swap',
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${interSans.variable} `}>
      <body>
        <Header />
        {children}
        <GetStart />
        <Footer />
      </body>
    </html>
  );
}
