import React from 'react';
import styles from './amlPolicy.module.scss';
import ButtonText from '@/components/buttonText';
const AML = '/assets/images/aml.png';
export default function AmlPolicy() {
    return (
        <div className={styles.amlPolicy}>
            <div className='container'>
                <div className={styles.center}>
                    <ButtonText text="Legal" />
                </div>
                <h1>AML Policy</h1>

                <div className={styles.contentWrapper}>
                    <p className={styles.lastUpdated}>(Last updated: 30 June 2026)</p>
                    <p className={styles.introText}>
                        ZeonFX Limited (“ZeonFX”) is committed to preventing money laundering, terrorist financing, and other financial crime. This Policy summarises the principles and controls ZeonFX applies to detect and deter the use of its services for illegal purposes, and the obligations that apply to clients. ZeonFX operates as an execution-only broker registered in Saint Lucia.
                    </p>

                    <div className={styles.section}>
                        <h2>1. Purpose and scope</h2>
                        <p>
                            The purpose of this Policy is to set out how ZeonFX identifies clients, monitors activity, and reports concerns, in line with international anti-money-laundering and counter-terrorist-financing standards. It applies to all clients, all accounts, and all transactions conducted through ZeonFX.
                        </p>
                        <p>
                            Money laundering is the process of making funds generated by criminal activity appear legitimate. ZeonFX has no tolerance for the use of its services to launder money or to finance terrorism, and cooperates with lawful requests from competent authorities.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>2. Know Your Customer (KYC)</h2>
                        <p>
                            Before a client can trade, deposit, or withdraw, ZeonFX applies a Know Your Customer process to verify identity and assess risk. ZeonFX may request the following, and may ask for updated or additional documents at any time:
                        </p>
                        <ul>
                            <li>Proof of identity: a valid government-issued document such as a passport, national identity card, or driving licence.</li>
                            <li>Proof of address: a recent utility bill, bank statement, or official document, typically issued within the last three to six months.</li>
                            <li>Proof of payment: verification of the payment instrument used to fund the account, such as a card or bank account in the client's name.</li>
                            <li>Additional information: date of birth, nationality, occupation, and contact details.</li>
                        </ul>
                        <p>
                            Accounts may remain restricted until verification is complete. ZeonFX may decline to open an account, or may suspend or close an account, where verification cannot be completed satisfactorily.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>3. Customer due diligence and risk-based approach</h2>
                        <p>
                            ZeonFX applies customer due diligence proportionate to the risk each client presents. Standard due diligence applies to most clients. Enhanced due diligence applies to higher-risk situations, which may include politically exposed persons, clients from higher-risk jurisdictions, or unusual account activity.
                        </p>
                        <p>
                            As part of its risk-based approach, ZeonFX screens clients against applicable sanctions lists, politically exposed persons lists, and adverse-media sources, both at onboarding and on an ongoing basis.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>4. Source of funds and source of wealth</h2>
                        <p>
                            Where appropriate, ZeonFX may ask clients to provide evidence of the source of the funds they deposit, and for higher-risk cases the source of their wider wealth. This helps confirm that funds are legitimate. Clients are expected to provide accurate information and supporting documents on request.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>5. Ongoing monitoring</h2>
                        <p>
                            ZeonFX monitors accounts and transactions on an ongoing basis to identify activity that is unusual, inconsistent with a client's profile, or without an apparent lawful purpose. Monitoring covers deposits, withdrawals, trading patterns, and changes to account information. Where activity raises concern, ZeonFX may request further information, delay or refuse a transaction, or take other appropriate steps.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>6. Deposits, withdrawals, and payment rules</h2>
                        <p>
                            To reduce money-laundering risk, ZeonFX applies the following principles to funding:
                        </p>
                        <ul>
                            <li>Third-party payments are not accepted. Funds must come from, and be returned to, an account or instrument in the client's own name.</li>
                            <li>Withdrawals are generally returned to the original funding source before any alternative method is considered.</li>
                            <li>ZeonFX may request additional verification before processing a deposit or withdrawal.</li>
                            <li>ZeonFX may decline or reverse transactions that cannot be reconciled with a client's verified profile.</li>
                        </ul>
                    </div>

                    <div className={styles.section}>
                        <h2>7. Reporting and cooperation</h2>
                        <p>
                            Where ZeonFX identifies activity it reasonably suspects to be linked to money laundering, terrorist financing, or other financial crime, it will take appropriate action, which may include reporting to the relevant authorities in accordance with applicable law. ZeonFX may be prohibited by law from informing a client that a report has been made.
                        </p>
                        <p>
                            ZeonFX cooperates with lawful requests for information from competent authorities and may freeze or restrict accounts where required to do so.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>8. Record keeping</h2>
                        <p>
                            ZeonFX keeps records of client identification, verification documents, and transactions for the period required by applicable law, typically several years after the end of the client relationship. These records are stored securely and are available to competent authorities when lawfully requested.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>9. Client responsibilities</h2>
                        <p>
                            By using ZeonFX services, clients agree to provide accurate, current, and complete information, to keep it up to date, and to supply verification documents on request. Clients must not use ZeonFX services to launder money, finance terrorism, or carry out any unlawful activity. Providing false information, or refusing reasonable verification requests, may result in account restriction, suspension, or closure.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>10. Consequences of non-compliance</h2>
                        <p>
                            ZeonFX reserves the right to refuse, restrict, suspend, or terminate any account, and to withhold or reverse transactions, where it has reasonable grounds to believe that this Policy or applicable law has been or may be breached. ZeonFX is not liable for losses arising from action taken in good faith to comply with its legal and regulatory obligations.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>11. Updates to this Policy</h2>
                        <p>
                            ZeonFX may update this Policy to reflect changes in law, regulation, or its own procedures. The current version is published on this page and takes effect on publication.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>12. Contact</h2>
                        <p>
                            For questions about this Policy, contact the ZeonFX compliance team at compliance@zeonfx.com or support@zeonfx.com.
                        </p>
                    </div>

                    <hr className={styles.divider} />

                    <h2>Restricted Countries</h2>
                    <p className={styles.lastUpdated}>(Last updated: 30 June 2026)</p>
                    <p className={styles.introText}>
                        ZeonFX Limited (“ZeonFX”) does not offer its services to residents or citizens of certain countries and jurisdictions. This section explains those restrictions and what they mean for prospective and existing clients.
                    </p>

                    <div className={styles.section}>
                        <h2>1. Restricted jurisdictions</h2>
                        <p>
                            ZeonFX does not open accounts for, or provide services to, residents or citizens of the following countries and jurisdictions:
                        </p>

                        <img src={AML} alt='AML' />
                    </div>

                    <div className={styles.section}>
                        <h2>2. Why these restrictions apply</h2>
                        <p>
                            These restrictions exist for a combination of legal, regulatory, and commercial reasons. In some cases, providing services would conflict with sanctions or with the laws of the jurisdiction concerned. In others, ZeonFX has chosen not to offer services in a market. The presence of a country on this list does not imply any judgement about that country beyond ZeonFX's decision not to serve it.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>3. General restriction</h2>
                        <p>
                            In addition to the specific list above, the services of ZeonFX are not intended for distribution to, or use by, any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation, or where ZeonFX is not authorised to offer them. It is your responsibility to ensure that your use of ZeonFX services is lawful in your country of residence.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>4. Client responsibility and verification</h2>
                        <p>
                            By opening an account, you confirm that you are not a resident or citizen of a restricted jurisdiction and that you are legally permitted to use ZeonFX services. ZeonFX verifies client identity and location as part of its onboarding and anti-money-laundering checks. If ZeonFX determines that an account has been opened from a restricted jurisdiction, or that a client has provided false information about their location or citizenship, ZeonFX may suspend or close the account and may restrict withdrawals pending review.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>5. Changes to this list</h2>
                        <p>
                            ZeonFX may update this list at any time to reflect changes in law, sanctions, or its own commercial decisions. The current version is published on this page and takes effect on publication. We encourage you to check it before using our services.
                        </p>
                    </div>

                    <div className={styles.section}>
                        <h2>6. Contact</h2>
                        <p>
                            If you are unsure whether services are available in your country, contact support@zeonfx.com before opening an account.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}

